fx_version 'adamant'
games { 'gta5' };

-- this_is_a_map 'yes'

client_scripts {
    "pmenu.lua",
    -- "main.lua",
    "config.lua",
    "@extendedmode/locale.lua",
    "divers/carwash/cl_carwash.lua",
    "locales/fr.lua",
    "garage/cl_garage.lua",
    "job/agentimmobilier/cl_immo.lua",
    "divers/location/cl_loc.lua",
    "divers/animation/cl_animation.lua",
    "job/unicorn/cl_unicorn.lua",
    "creator/cl_creator.lua",
    "divers/sitchair/cl_sitchair.lua",
    "job/mecano/cl_mecano.lua",
    "job/tatouage/cl_tattoo.lua",
    "society/cl_society.lua",
    "divers/cayoperico/cl_cayoperico.lua",
    "divers/cayoperico/cutscenes.lua",
    "divers/cayoperico/dlc_loader.lua",
    "admin/cl_admin.lua",
    "divers/skin/cl_skin.lua",
    "divers/ltd/cl_ltd.lua",
    "divers/f7/cl_f7.lua",
    "divers/pawnshop/cl_pawnshop.lua",
    "function.lua",
    "weather/cl_weather.lua",
    "job/barber/cl_barber.lua",
    'divers/ammunation/cl_ammunation.lua',
    "divers/blip/blip.lua",
    "peche/cl_peche.lua",
    "divers/essence/cl_essence.lua",
    "menuf5/cl_f5.lua",
    "identity/cl_identity.lua",
    "divers/ped/cl_ped.lua",
    "divers/vehiclelock/cl_vehiclelock.lua",
    "divers/3dme/cl_3dme.lua",
    "divers/billing/cl_billing.lua",
    "useitem/cl_use.lua",
    'autoecole/cl_autoecole.lua',
    "job/police/cl_police.lua",
    "job/concessionnaire/cl_concess.lua",
    "job/mecano/cl_custom.lua",
    "job/restaurant/cl_restaurant.lua",
    "job/burgershot/cl_burgershot.lua",
    "job/ambulance/cl_ambulance.lua",
    "ipl/lib/common.lua", 
    "ipl/lib/observers/*.lua", 
    "ipl/client.lua",
    "atm/cl_atm.lua",
    "weaponitem/cl_weaponitem.lua",
    "braquage/cl_braquage.lua",
  	"ipl/gtav/*.lua",
	"ipl/gta_online/*.lua",
  	"ipl/dlc_high_life/*.lua",
	"ipl/dlc_heists/*.lua",
	"ipl/dlc_executive/*.lua",
	"ipl/dlc_finance/*.lua",
  	"ipl/dlc_bikers/*.lua",
	"ipl/dlc_import/*.lua",
	"ipl/dlc_gunrunning/*.lua",
	"ipl/dlc_smuggler/*.lua",
	"ipl/dlc_doomsday/*.lua",
	"ipl/dlc_afterhours/*.lua",
    "deathevents.lua",
    "client.lua",
    "vehiclechecker",
}

server_scripts {
    "@mysql-async/lib/MySQL.lua",
    "@extendedmode/locale.lua",
    "config.lua",
    'job/mecano/sv_mecano.lua',
    'job/police/sv_police.lua',
    "divers/billing/sv_billing.lua",
    "divers/essence/sv_essence.lua",
    "divers/ltd/sv_ltd.lua",
    'divers/ammunation/sv_ammunation.lua',
    "divers/cayoperico/sv_cayoperico.lua",
    "peche/sv_peche.lua",
    "braquage/sv_braquage.lua",
    "atm/sv_atm.lua",
    "weaponitem/sv_weaponitem.lua",
    "divers/carwash/sv_carwash.lua",
    "weather/sv_weather.lua",
    "divers/location/sv_loc.lua",
    "divers/3dme/sv_3dme.lua",
    'job/mecano/sv_custom.lua',
    "society/sv_society.lua",
    "identity/sv_identity.lua",
    "job/restaurant/sv_restaurant.lua",
    "job/burgershot/sv_burgershot.lua",
    "garage/sv_garage.lua",
    "useitem/sv_use.lua",
    "divers/pawnshop/sv_pawnshop.lua",
    "divers/vehiclelock/sv_vehiclelock.lua",
    'creator/sv_creator.lua',
    'autoecole/sv_autoecole.lua',
    "divers/skin/sv_skin.lua",
    "job/concessionnaire/sv_concess.lua",
    "job/tatouage/sv_tattoo.lua",
    "admin/sv_admin.lua",
    "job/agentimmobilier/sv_immo.lua",
    "job/barber/sv_barber.lua",
    "job/unicorn/sv_unicorn.lua",
    "job/ambulance/sv_ambulance.lua",
}

files {
    'index.html',
    'ui.html',
    'style.css',
    'bg/*.png',
    'sound/zbase.ogg',
    "AllTattoos.json"
    -- 'gabz_timecycle_mods_1.xml'
}

-- data_file 'TIMECYCLEMOD_FILE' 'gabz_timecycle_mods_1.xml'

loadscreen 'index.html'

ui_page 'ui.html'